// Actions
const RELOAD_ROUTE = 'RELOAD_ROUTE';
const SYNC_CHAT_SESSIONS = 'SYNC_CHAT_SESSIONS';
const SYNC_CHAT_MESSAGES = 'SYNC_CHAT_MESSAGES';
const ADD_CHAT_SESSION = 'ADD_CHAT_SESSION';
const UPDATE_CHAT_SESSION = 'UPDATE_CHAT_SESSION';
const UPDATE_CHAT_SESSION_IF_EDITED = 'UPDATE_CHAT_SESSION_IF_EDITED';
const DELETE_CHAT_SESSION = 'DELETE_CHAT_SESSION';
const SET_ACTIVE = 'SET_ACTIVE';
const SET_ACTIVE_LOCAL = 'SET_ACTIVE_LOCAL';
const ADD_CHAT_BY_UUID = 'ADD_CHAT_BY_UUID';
const UPDATE_CHAT_BY_UUID = 'UPDATE_CHAT_BY_UUID';
const UPDATE_CHAT_PARTIAL_BY_UUID = 'UPDATE_CHAT_PARTIAL_BY_UUID';
const DELETE_CHAT_BY_UUID = 'DELETE_CHAT_BY_UUID';
const CLEAR_CHAT_BY_UUID = 'CLEAR_CHAT_BY_UUID';
const CLEAR_STATE = 'CLEAR_STATE';
