import activeChatReducer, {
  setIsGenerating,
  setFirstTokenReceived,
  setAbortController,
  setIsDisabled,
  setActiveLocal,
} from './activeChatSlice';
import assistantReducer, {
  setAssistantImages,
  setAssistants,
  setOpenaiAssistants,
  setSelectedAssistant,
} from './assistantSlice';
import baseChatReducer, {
  setLoading,
  setError,
  setChatRequestData,
  setApiKey,
  setWorkspaceId,
  setSessionId,
  setActiveSession,
} from './baseChatSlice';
import chatInputCommandReducer, {
  setIsPromptPickerOpen,
  setSlashCommand,
  setFocusPrompt,
  setFocusFile,
  setFocusTool,
  setFocusAssistant,
  setAtCommand,
  setIsAssistantPickerOpen,
  setIsFilePickerOpen,
  setIsToolPickerOpen,
  setToolCommand,
  setHashtagCommand,
} from './chatInputCommandSlice';
import collectionReducer, { setCollections } from './collectionSlice';
import fileReducer, {
  setChatFiles,
  setFiles,
  setChatImages,
  setNewMessageImages,
  setNewMessageFiles,
  setShowFilesDisplay,
  fetchFileData,
  setPreviewFiles,
  setSelectedFiles,
  setPreviewUrls,
  setUploadedFiles,
} from './fileSlice';
import foldersReducer, { setFolders, setSelectedFolder } from './foldersSlice';
import generalChatReducer, {
  setEnvKeyMap,
  setChats,
  setChat,
} from './generalChatSlice';
import modelsReducer, {
  setAvailableHostedModels,
  setAvailableLocalModels,
  setAvailableOpenRouterModels,
  setModels,
} from './modelsSlice';
import passiveChatReducer, {
  setUserInput,
  setChatMessages,
  setChatSettings,
  setSelectedChat,
  setChatFileItems,
  setPayload,
} from './passiveChatSlice';
import presetReducer, { setPresets, setSelectedPreset } from './presetSlice';
import promptReducer, { setPrompts, setSelectedPrompt } from './promptSlice';
import retrievalReducer, {
  setSourceCount,
  setUseRetrieval,
} from './retrievalSlice';
import toolReducer, {
  setSelectedTools,
  setToolInUse,
  setTools,
} from './toolSlice';
import workspaceReducer, {
  setWorkspaces,
  setSelectedWorkspace,
  setWorkspaceImages,
  setHomeWorkSpace,
  setActiveWorkspace,
  setChatSessions,
} from './workspaceSlice';

export {
  setPayload,
  setSelectedFiles,
  setPreviewUrls,
  setPresets,
  setSelectedPreset,
  setAssistantImages,
  setAssistants,
  setOpenaiAssistants,
  setSelectedAssistant,
  setLoading,
  setError,
  setChatRequestData,
  setApiKey,
  setWorkspaceId,
  setSessionId,
  setActiveSession,
  setIsGenerating,
  setFirstTokenReceived,
  setAbortController,
  setIsDisabled,
  setActiveLocal,
  setIsPromptPickerOpen,
  setSlashCommand,
  setFocusPrompt,
  setFocusFile,
  setFocusTool,
  setFocusAssistant,
  setAtCommand,
  setIsAssistantPickerOpen,
  setIsFilePickerOpen,
  setIsToolPickerOpen,
  setToolCommand,
  setHashtagCommand,
  setCollections,
  setChatFiles,
  setFiles,
  setChatImages,
  setNewMessageImages,
  setNewMessageFiles,
  setShowFilesDisplay,
  setFolders,
  setSelectedFolder,
  setEnvKeyMap,
  setChats,
  setChat,
  setAvailableHostedModels,
  setAvailableLocalModels,
  setAvailableOpenRouterModels,
  setModels,
  setUserInput,
  setChatMessages,
  setChatSettings,
  setSelectedChat,
  setChatFileItems,
  setPrompts,
  setSelectedPrompt,
  setSourceCount,
  setUseRetrieval,
  setWorkspaces,
  setSelectedWorkspace,
  setWorkspaceImages,
  setHomeWorkSpace,
  setSelectedTools,
  setToolInUse,
  setTools,
  fetchFileData,
  setPreviewFiles,
  setUploadedFiles,
  setActiveWorkspace,
  setChatSessions,
};

export {
  activeChatReducer,
  assistantReducer,
  baseChatReducer,
  chatInputCommandReducer,
  collectionReducer,
  fileReducer,
  foldersReducer,
  generalChatReducer,
  modelsReducer,
  passiveChatReducer,
  presetReducer,
  promptReducer,
  retrievalReducer,
  toolReducer,
  workspaceReducer,
};
