/* eslint-disable import/order */
import workspaceReducer, {
  setWorkspaces,
  setSelectedWorkspace,
  setWorkspaceImages,
  setHomeWorkSpace,
  setActiveWorkspace,
  setWorkspaceId,
} from './workspaceSlice';
import baseChatReducer, {
  setLoading,
  setError,
  setChatRequestData,
  setApiKey,
  setIsGenerating,
  setFirstTokenReceived,
  setAbortController,
  setIsDisabled,
  setActiveLocal,
  setIsMessagesUpdated,
  setFirstMessageReceived,
  setUserInput,
  setChatMessages,
  setChatSettings,
  setSelectedChat,
  setChatFileItems,
  setPayload,
  setEnvKeyMap,
  setIsPromptPickerOpen,
  setSlashCommand,
  setFocusPrompt,
  setFocusFile,
  setFocusTool,
  setFocusAssistant,
  setAtCommand,
  setIsAssistantPickerOpen,
  setIsFilePickerOpen,
  setIsToolPickerOpen,
  setToolCommand,
  setHashtagCommand,
  setSourceCount,
  setUseRetrieval,
  // setSessionId,
  // setActiveSession,
} from './baseChatSlice';
import chatSessionReducer, {
  setChatSessions,
  setSelectedChatSession,
  setSessionId,
  setSessionHeader,
  setActiveSession,
  createChatSession,
} from './chatSessionSlice';
import assistantReducer, {
  setAssistantImages,
  setAssistants,
  setOpenaiAssistants,
  setSelectedAssistant,
} from './assistantSlice';
import collectionReducer, { setCollections } from './collectionSlice';
import fileReducer, {
  setChatFiles,
  setFiles,
  setChatImages,
  setNewMessageImages,
  setNewMessageFiles,
  setShowFilesDisplay,
  fetchFileData,
  setPreviewFiles,
  setSelectedFiles,
  setPreviewUrls,
  setUploadedFiles,
} from './fileSlice';
import folderReducer, { setFolders, setSelectedFolder } from './foldersSlice';
import modelReducer, {
  setAvailableHostedModels,
  setAvailableLocalModels,
  setAvailableOpenRouterModels,
  setModels,
  setSelectedModel,
} from './modelsSlice';
import presetReducer, { setPresets, setSelectedPreset } from './presetSlice';
import promptReducer, { setPrompts, setSelectedPrompt } from './promptSlice';
import toolReducer, {
  setSelectedTools,
  setToolInUse,
  setTools,
} from './toolSlice';

export {
  setPayload,
  setSelectedFiles,
  setPreviewUrls,
  setPresets,
  setSelectedPreset,
  setAssistantImages,
  setAssistants,
  setOpenaiAssistants,
  setSelectedAssistant,
  setLoading,
  setError,
  setChatRequestData,
  setApiKey,
  setWorkspaceId,
  setSessionId,
  setActiveSession,
  setIsGenerating,
  setFirstTokenReceived,
  setAbortController,
  setIsDisabled,
  setActiveLocal,
  setIsPromptPickerOpen,
  setSlashCommand,
  setFocusPrompt,
  setFocusFile,
  setFocusTool,
  setFocusAssistant,
  setAtCommand,
  setIsAssistantPickerOpen,
  setIsFilePickerOpen,
  setIsToolPickerOpen,
  setToolCommand,
  setHashtagCommand,
  setCollections,
  setChatFiles,
  setFiles,
  setChatImages,
  setNewMessageImages,
  setNewMessageFiles,
  setShowFilesDisplay,
  setFolders,
  setSelectedFolder,
  setSessionHeader,
  setEnvKeyMap,
  createChatSession,
  // setChats,
  // setChat,
  setAvailableHostedModels,
  setAvailableLocalModels,
  setAvailableOpenRouterModels,
  setModels,
  setUserInput,
  setChatMessages,
  setChatSettings,
  setSelectedChat,
  setChatFileItems,
  setPrompts,
  setSelectedPrompt,
  setSourceCount,
  setUseRetrieval,
  setWorkspaces,
  setSelectedWorkspace,
  setWorkspaceImages,
  setHomeWorkSpace,
  setSelectedTools,
  setToolInUse,
  setTools,
  fetchFileData,
  setPreviewFiles,
  setUploadedFiles,
  setActiveWorkspace,
  setChatSessions,
  setIsMessagesUpdated,
  setFirstMessageReceived,
  setSelectedChatSession,
  setSelectedModel,
};

export {
  workspaceReducer,
  baseChatReducer,
  chatSessionReducer,
  fileReducer,
  folderReducer,
  assistantReducer,
  collectionReducer,
  modelReducer,
  presetReducer,
  promptReducer,
  toolReducer,
};
// import generalChatReducer, {
//   setEnvKeyMap,
//   setChats,
//   setChat,
// } from './generalChatSlice';
// import retrievalReducer, {
//   setSourceCount,
//   setUseRetrieval,
// } from './retrievalSlice';
// import chatInputCommandReducer, {
//   setIsPromptPickerOpen,
//   setSlashCommand,
//   setFocusPrompt,
//   setFocusFile,
//   setFocusTool,
//   setFocusAssistant,
//   setAtCommand,
//   setIsAssistantPickerOpen,
//   setIsFilePickerOpen,
//   setIsToolPickerOpen,
//   setToolCommand,
//   setHashtagCommand,
// } from './chatInputCommandSlice';
// import activeChatReducer, {
//   setIsGenerating,
//   setFirstTokenReceived,
//   setAbortController,
//   setIsDisabled,
//   setActiveLocal,
//   setIsMessagesUpdated,
//   setFirstMessageReceived,
// } from './activeChatSlice';
// import passiveChatReducer, {
//   setUserInput,
//   setChatMessages,
//   setChatSettings,
//   setSelectedChat,
//   setChatFileItems,
//   setPayload,
// } from './passiveChatSlice';
