import BugReportIcon from '@mui/icons-material/BugReport';
import PendingIcon from '@mui/icons-material/Pending';

import { uniqueId } from 'lodash';
import {
  DashboardIcon,
  HomeIcon,
  LoginIcon,
  ArticleIcon,
  ChatIcon,
  CodeIcon,
  ColorLensIcon,
  ErrorIcon,
  NoteAddIcon,
  PersonIcon,
  TableChartIcon,
  LockIcon,
} from 'assets/humanIcons';
const base = `${window.location.origin}`;
const host = 'http://localhost:3000';

export const templatesData = [
  {
    id: uniqueId('templates-test-'),
    title: 'Test Home',
    name: 'Test Home',
    description: 'Chat Test Description',
    functionalStatus: true,
    icon: <BugReportIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/test/test-home',
    route: `${base}/test/test-home`,
    link: `${base}/test/test-home`,
    a: `${host}/test/test-home`,
  },
  {
    id: uniqueId('templates-test-'),
    title: 'Chat Test',
    name: 'Chat Test',
    description: 'Chat Test Description',
    functionalStatus: true,
    icon: <ChatIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/test/chat-test',
    route: `${base}/test/chat-test`,
    link: `${base}/test/chat-test`,
    a: `${host}/test/chat-test`,
  },
  {
    id: uniqueId('templates-test-'),
    title: 'Loaders Test',
    description: 'Loaders Test Description',
    functionalStatus: true,
    icon: <PendingIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    route: `${base}/test/loaders-test`,
    link: `${base}/test/loaders-test`,
    name: 'Loaders Test',
    path: '/test/loaders-test',
    a: `${host}/test/loaders-test`,
    // breadcrumb: 'Loaders Test',
    // element: <LoadersDisplay />,
    // errorElement: <RootErrorBoundary />,
    // collapse: false,
  },
  {
    id: uniqueId('templates-land-'),
    title: 'Landing',
    name: 'Landing',
    description: 'Landing Page',
    icon: <HomeIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/hero-docs',
    route: `${base}/hero-docs`,
    link: `${base}/hero-docs`,
  },
  {
    id: uniqueId('templates-admin-'),
    title: 'Main Dashboard',
    name: 'Main Dashboard',
    description: 'Main Dashboard Description',
    icon: <DashboardIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/dashboard',
    route: `${base}/admin/dashboard`,
    link: `${base}/admin/dashboard`,
  },
  {
    id: uniqueId('templates-admin-'),
    title: 'Data Tables',
    name: 'Data Tables',
    description: 'Data Tables Description',
    icon: <TableChartIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/data-tables',
    route: `${base}/admin/data-tables`,
    link: `${base}/admin/data-tables`,
  },
  {
    id: uniqueId('templates-admin-'),
    title: 'Templates',
    name: 'Templates',
    description: 'Templates Description',
    icon: <ColorLensIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/templates',
    route: `${base}/admin/templates`,
    link: `${base}/admin/templates`,
  },
  {
    id: uniqueId('templates-admin-'),
    title: 'Profile',
    name: 'Profile',
    description: 'Profile Description',
    icon: <PersonIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/profile',
    route: `${base}/admin/profile`,
    link: `${base}/admin/profile`,
  },
  {
    id: uniqueId('templates-'),
    type: 'template',
    title: 'Original Chat Ai',
    name: 'Original Chat Ai',
    description: 'Original Chat Ai Description',
    functionalStatus: true,
    icon: <ChatIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/templates/original-chat-ai',
    route: `${base}/admin/templates/original-chat-ai`,
    link: `${base}/admin/templates/original-chat-ai`,
    a: `${host}/admin/templates/original-chat-ai/*`,
  },
  {
    id: uniqueId('templates-'),
    type: 'template',
    title: 'Blog Post Generator',
    name: 'Blog Post Generator',
    description: 'Blog Post Generator Description',
    functionalStatus: false,
    icon: <ArticleIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/templates/blog-post',
    route: `${base}/admin/templates/blog-post`,
    link: `${base}/admin/templates/blog-post`,
    a: `${host}/admin/templates/blog-post/*`,
  },
  {
    id: uniqueId('templates-'),
    type: 'template',
    title: 'Code Converter',
    name: 'Code Converter',
    description: 'Code Converter Description',
    icon: <CodeIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/templates/code-converter',
    route: `${base}/admin/templates/code-converter`,
    link: `${base}/admin/templates/code-converter`,
    a: `${host}/admin/templates/code-converter/*`,
  },
  {
    id: uniqueId('templates-'),
    type: 'template',
    title: 'Editor',
    name: 'Editor',
    description: 'Editor Description',
    icon: <CodeIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/templates/editor',
    route: `${base}/admin/templates/editor`,
    link: `${base}/admin/templates/editor`,
    a: `${host}/admin/templates/editor/*`,
  },
  {
    id: uniqueId('templates-'),
    type: 'template',
    title: 'Theme Generator',
    name: 'Theme Generator',
    description: 'Theme Generator Description',
    icon: <ColorLensIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/templates/theme-generator',
    route: `${base}/admin/templates/theme-generator`,
    link: `${base}/admin/templates/theme-generator`,
    a: `${host}/admin/templates/theme-generator`,
  },
  {
    id: uniqueId('templates-'),
    type: 'template',
    title: 'Template Generator',
    name: 'Template Generator',
    description: 'Template Generator Description',
    icon: <NoteAddIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/admin/templates/generate-template',
    route: `${base}/admin/templates/generate-template`,
    link: `${base}/admin/templates/generate-template`,
    a: `${host}/admin/templates/generate-template`,
  },
  {
    id: uniqueId('template-'),
    title: 'Not Found',
    name: 'Not Found',
    description: 'Page Not Found',
    icon: <ErrorIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '*',
    route: `${base}/*`,
    link: `${base}/*`,
  },
  {
    id: uniqueId('template-auth-'),
    title: 'Sign In',
    name: 'Sign In',
    description: 'Sign In Page',
    icon: <LoginIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/auth/sign-in',
    route: `${base}/auth/sign-in`,
    link: `${base}/auth/sign-in`,
  },
  {
    id: uniqueId('template-auth-'),
    title: 'Sign Up',
    name: 'Sign Up',
    description: 'Sign Up Page',
    icon: <LockIcon sx={{ width: 20, height: 20, color: 'inherit' }} />,
    path: '/auth/sign-up',
    route: `${base}/auth/sign-up`,
    link: `${base}/auth/sign-up`,
  },
];

export default templatesData;
